version: "3.9"

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_FILE: .env
    entrypoint:
      sh -c "
      alembic upgrade head &&
      uvicorn src.main:app --host 0.0.0.0 --reload
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      web_db:
          condition: service_healthy
    networks:
      - web_net

  web_db:
    image: postgres:10.1-alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_NAME=restra
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restra"]
      interval: 5s
      timeout: 10s
      retries: 30

networks:
  web_net:
    name: web_net