"""init

Revision ID: 370b7ed8d0e9
Revises:
Create Date: 2023-01-22 11:56:39.988769

"""
import sqlalchemy as sa
import sqlalchemy_utils as su
from alembic import op

# revision identifiers, used by Alembic.
revision = "370b7ed8d0e9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", su.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submenus",
        sa.Column("id", su.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("Menu", su.types.uuid.UUIDType(binary=False), nullable=True),
        sa.ForeignKeyConstraint(["Menu"], ["menus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dishes",
        sa.Column("id", su.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=False),
        sa.Column("SubMenu", su.types.uuid.UUIDType(binary=False), nullable=True),
        sa.ForeignKeyConstraint(["SubMenu"], ["submenus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dishes")
    op.drop_table("submenus")
    op.drop_table("menus")
    # ### end Alembic commands ###
