"""initial

Revision ID: 4cce1e4306ab
Revises: 
Create Date: 2023-01-22 01:40:46.435624

"""
import sqlalchemy_utils as su
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cce1e4306ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', su.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submenus',
    sa.Column('id', su.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('Menu', su.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['Menu'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('id', su.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('SubMenu', su.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['SubMenu'], ['submenus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
